---
# configuration options for description service

# number of max image bitstream that description service will extract for pdf document,
# comment out to set max image bitstream extraction unlimited
max-pdf-bitstreams: 1000

# jvm options
#jvm-options:
#  - -Xms16m 
#  - -Xmx32m
#  - -Dhttp.proxyHost=localhost
#  - -Dhttp.proxyPort=3128
