---
# configuration options for description service

# number of max image bitstream that description service will extract for pdf document,
# comment out to set max image bitstream extraction unlimited
max-pdf-bitstreams: 1000

# specify the log file to be used for the description service logging.  
# Comment out to dump logs to standard output.
log-file: DescribeService.log

# jvm options to be passed to the jvm.
# http.proxyHost, http.proxyPort- the host name and port number of the proxy server.  
# For exmample, users can specify the web cache server to be used for xml validation.
jvm-options:
  - -Dhttp.proxyHost=localhost
  - -Dhttp.proxyPort=3128
